### ISSUE TITLE
Issues while runing node.js

### ISSUE THREAD

**Issue by YoungJimmy** [jainanshul/caltech-pedestrian-dataset-extractor#7]
After runing "node caltech_pd.js" under path "caltech-pedestrian-dataset-extractor" ,there is a Issue.As follow:
module.js:339
    throw err;
    ^

Error: Cannot find module './build/Release/fs-ext'
    at Function.Module._resolveFilename (module.js:337:15)
    at Function.Module._load (module.js:287:25)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/zqy/Desktop/lstm-rcnn-pedestrian-detection/caltech-dataset/caltech-pedestrian-dataset-extractor/node_modules/fs-ext/fs-ext.js:20:15)
    at Module._compile (module.js:435:26)
    at Object.Module._extensions..js (module.js:442:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:311:12)
    at Module.require (module.js:366:17)

So I run "npm install -g fs-ext" under path "caltech-pedestrian-dataset-extractor", but there is a new issue.As follow:
npm ERR! Linux 4.4.0-31-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "fs-ext"
npm ERR! node v4.2.1
npm ERR! npm  v2.14.7
npm ERR! code ENOTFOUND
npm ERR! errno ENOTFOUND
npm ERR! syscall getaddrinfo

npm ERR! network getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
npm ERR! network This is most likely not a problem with npm itself
npm ERR! network and is related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network 
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! Please include the following file with any support request:
npm ERR!     /home/zqy/Desktop/lstm-rcnn-pedestrian-detection/caltech-dataset/caltech-pedestrian-dataset-extractor/node_modules/npm-debug.log

How to fix it?

**Comment by YoungJimmy** [comment]
I have try updating npm version to 5.3.0, and node version to v8.2.1. but it doesn't seem work when runing "npm install -g fs-ext" under path "caltech-pedestrian-dataset-extractor". As follows:

npm ERR! code MODULE_NOT_FOUND
npm ERR! Cannot find module 'internal/fs'

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-07-28T04_46_59_992Z-debug.log

**Comment by jainanshul** [comment]
`npm install -g fs-ext` works fine for me. I am on node version `v6.6.0` and npm version `3.10.8`

**Comment by YoungJimmy** [comment]
Alright, thank u. I just try it on node version v6.6.0.
